# Output directory
OUTPUT_DIR = bin

# Default flags
CFLAGS_INTERNAL = -I$(SROOT)/src/Include
LDFLAGS_INTERNAL = -Lbin/

# Programs
SUBDIRS_BIN = TEST1
SUBDIRS_SBIN = TEST2
SUBDIRS_LIB = TEST3
SUBDIRS_OBJONLY = TEST4
SUBDIRS_LIBEXEC = TEST5

# Per program settings
TEST1_OBJS = TEST4
TEST1_CFLAGS =
TEST1_LIBS = TEST3

TEST2_OBJS = TEST4
TEST2_CFLAGS =
TEST2_LIBS = TEST3

TEST5_OBJS = TEST4
TEST5_CFLAGS =
TEST5_LIBS = TEST3

# Data files
INSTALL_INCLUDES = src/Include
INSTALL_ETCS = etc
INSTALL_SHARE = share
INSTALL_LOCALES = locale

# Documents
INSTALL_DOCS = doc/main
INSTALL_DOCS_INFO = doc/info
INSTALL_DOCS_MAN = doc/man
INSTALL_DOCS_DVI = doc/dvi
INSTALL_DOCS_PDF = doc/pdf
INSTALL_DOCS_PS = doc/ps
